<?php
require 'header.php';
?>

<div id="avis-legal" class="container top40 bottom80">
    <div class="row userPanelSectionBox">

        <h1 class="bottom20">Avís Legal</h1>
        <h2>1. Objecte</h2>
        <div>
            <p>El lloc web <a href="index.php">Musicalitza</a> i la seva versió per a dispositius mòbils com smartphones o tablets (en endavant, el “<strong>Portal</strong>”) pertany a i és gestionat per (nom del titular), amb NIF nº XXXXXXXXX i domicili a Igualada (Barcelona) (en endavant, el “<strong>Titular</strong>” o “<strong>Musicalitza</strong>”). Per comunicar-se amb el Titular, de manera directa i efectiva, pots fer-ho a través de l’adreça de correu electrònic <a href="mailto: admin@ioc-musicalitza.tk"><em> admin@ioc-musicalitza.tk</em></a>.</p>
            <p>Aquest Avís Legal per a Usuaris regula l’accés i l’ús del Portal i dels seus continguts (en endavant, les “<strong>Condicions Generals d’Ús</strong>”), així com les condicions de contractació entre Musicalitza i els clients o usuaris del Portal (en endavant, les “<strong>Condicions Generals de Contractació per a Clients</strong>”).</p>
            <p>Sens perjudici de l’anterior, l’accés a determinats continguts i la utilització o contractació de determinats serveis poden estar subjectes a determinades condicions particulars (en endavant, les “<strong>Condicions Particulars</strong>”), que, segons els casos, substituiran, completaran i/o modificaran les respectives Condicions Generals d’Ús/Contractació i, en cas de conflicte, prevaldran per sobre de les Condicions Generals d’Ús/Contractació.</p>
            <p>La mera navegació per o utilització del Portal atribueix la condició d’usuari del Portal (en endavant, l’“<strong>Usuari</strong>”) i implica l’acceptació d’aquest Avís Legal i de totes les Condicions Generals d’Ús, de la Política de Privacitat i Cookies, sense cap reserva, així com, si escau, de les Condicions Particulars que puguin complementar-les, substituir-les o modificar-les en algun sentit en relació amb els serveis i continguts del Portal. Si no estàs d’acord amb aquests termes o amb la nostra Política de Privacitat i Cookies, et demanem que t’abstinguis d’utilitzar aquest Portal o els serveis que s’hi ofereixen. En cas contrari, considerarem que hi ha plena acceptació per part teva.</p>
            <p>En conseqüència, recomanem a tot Usuari que llegeixi amb atenció les Condicions Generals d’Ús i de Contractació recollides en aquest Avís Legal per a Usuaris cada vegada que accedeixi o utilitzi el Portal, així com, si escau, les corresponents Condicions Particulars. L’Usuari podrà accedir, imprimir, descarregar i guardar les Condicions Generals d’Ús i de Contractació en tot moment. Aquestes condicions estaràn permanentment accessibles en el Portal a través de l’enllaç de l’Avís Legal per a Usuaris.</p>
            En tot cas, el Titular es reserva el dret de modificar, en qualsevol moment i sense necessitat de preavís, el disseny, els continguts, la presentació i la configuració del Portal, la Política de Privacitat i Cookies, les Condicions Generals d’Ús, les corresponents Condicions Particulars, així com alguns o tots els serveis del Portal, i afegir-ne de nous. Per això, es recomana a Usuaris i Clients que consultin aquest Avís Legal per a Usuaris cada vegada que utilitzin el Portal o qualsevol dels seus serveis. En qualsevol cas, Musicalitza es reserva el dret de, en qualsevol moment i sense necessitat de preavís, denegar l’accés a aquest Portal a aquells Usuaris que incompleixin les Condicions Generals d’Ús o de Contractació, així com, si escau, les Condicions Particulars que siguin d’aplicació.<br><br><br></div>
        <div></div>
        <h2>2. Condicions generals d'ús del portal</h2>
        <hr><h3>2.1  Finalitat i serveis del Portal</h3>
        <div>
            <p>Les Condicions Generals d’Ús regulen l’accés i l’ús del Portal, la finalitat del qual és la de que els seus usuaris puguin coneixer i socialitzar amb altres usuaris amb afinitats musicals a partir de puntuar i crear-se una llista d'artistes i albums favorits (en endavants els "<strong>Artistes</strong>" i els "<strong>Albums</strong>").</p>
        </div>
        <h3><br>2.2  Drets i obligacions dels Usuaris</h3>
        <div>
            <p>Musicalitza és un servei gratuït al qual qualsevol usuari de qualsevol part del món pot accedir i disfrutar.</p>
            <p>L’Usuari es compromet a fer ús de la informació, els continguts i els serveis als quals accedeixi des del Portal, respectant la Llei, els bons costums i les condicions generals establertes en aquest Avís Legal, i respectant també la resta d’Usuaris.</p>
            <p>L’Usuari és conscient i accepta voluntàriament i expressament que l’ús del Portal es realitza en tot cas sota la seva única i exclusiva responsabilitat, i es compromet a no dur a terme cap conducta que pogués danyar la imatge, els interessos i els drets de Musicalitza, dels Artistes o de tercers, o que pogués danyar, inutilitzar, sobrecarregar o, de qualsevol forma, impedir la normal utilització del Portal. En conseqüència, l’Usuari renuncia a utilitzar qualsevol dels materials, informacions o continguts d’aquest Portal amb finalitats il·lícites i expressament prohibides en aquest Avís Legal, i que resultin contràries als drets i interessos de Musicalitza, dels Artistes i/o de tercers, i respondrà davant d’aquests en cas de contravenir o incomplir les referides obligacions o si, de qualsevol manera (inclosa la introducció o difusió de virus informàtics) la seva actuació contribueix a danyar, inutilitzar, sobrecarregar, deteriorar o impedir la normal utilització del Portal i dels seus continguts, els sistemes d’informació o els documents, arxius i tota classe de continguts emmagatzemats en qualsevol equip informàtic del Titular o d’algun Usuari del Portal.</p>
            <p>En cas que l’Usuari enviï informació o continguts de qualsevol tipus a Musicalitza a través del Portal, mitjançant els canals habilitats en aquest sentit al propi Portal, l’Usuari declara, garanteix i accepta que té dret a fer-ho lliurement, que la referida informació o continguts no infringeixen cap dret de propietat intel·lectual o industrial, secret comercial, o qualsevol altre dret de tercers, que la referida informació o continguts no tenen caràcter confidencial i que no són perjudicials per a tercers. L’Usuari serà l’únic responsable de la veracitat i l’actualització de la informació, els continguts i les dades que proporcioni al Titular, garantint en tot moment la seva veracitat i exactitud.</p>
            <p>L’Usuari no ha d’enviar al Titular cap mena d’informació confidencial sense haver-ho consultat prèviament amb el Titular i haver rebut la seva autorització per a enviar-li la referida informació.</p>
            <p>L’Usuari assumeix la responsabilitat i n’eximeix al Titular per qualsevol comunicació que proporcioni personalment o en el seu nom, incloent-hi sense cap mena de restricció l’exactitud, la legalitat, l’originalitat i la titularitat de la referida comunicació.</p>
            <p>L’Usuari es compromet a no dur a terme conductes considerades com a “spam”, com per exemple enviar publicitat de qualsevol mena o comunicacions amb finalitats de venda o altres de naturalesa comercial a una o més persones sense la seva prèvia sol·licitud o el consentiment exprés i informat, enviar cadenes d’emails no sol·licitats ni prèviament consentits, o utilitzar llistes de distribució a les quals pugui accedir a través del Portal per a la realització d’aquestes activitats.</p>
            <p>L’Usuari es compromet a no introduir en l’apartat destinat a puntuacions, comentaris i valoracions dels Albums, o en qualsevol altra secció del Portal, informació personal o comercial susceptible de facilitar el contacte directe entre Usuaris o entre Usuari i Artista, o apta per a realitzar qualsevol transacció comercial al marge de Musicalitza. En aquest sentit, queda expressament prohibida la introducció d’emails, telèfons, informació de contacte en xarxes socials o qualsevol altra dada personal apta per a aquestes finalitats.</p>
            <p>Queda expressament prohibit a l’Usuari realitzar les següents accions: (i) utilitzar mecanismes, software o scripts en relació amb l’ús del Portal; (ii) bloquejar, sobreescriure, modificar o copiar dades o continguts del Portal, llevat que sigui necessari per a la correcta utilització dels serveis del Portal. Per exemple, el copiat mitjançant tecnologies de buscador del tipus “robot/crawler” no és necessari per a la correcta utilització dels serveis del Portal, de manera que està prohibit expressament; (iii) reproduir i/o comunicar públicament continguts del Portal, dels Artistes o d’altres Usuaris, sense la preceptiva autorització prèvia del Titular o de les persones interessades; (iv) tota acció apta per a perjudicar la funcionalitat de la infraestructura de Musicalitza, especialment per a sobrecarregar-la; (v) utilitzar qualsevol dels continguts del Portal amb finalitats il·lícites i/o expressament prohibides en aquestes Condicions Generals d’Ús, així com en les condicions particulars que, si escau, s’habilitin, que resultin contràries als drets i interessos de Musicalitza, dels seus Artistes i Usuaris i/o de tercers. L’Usuari haurà de respondre en cas de contravenir o incomplir aquestes obligacions  o que, de qualsevol manera (inclosa la introducció o difusió de virus informàtics), danyi, inutilitzi, sobrecarregui, deteriori o impedeixi la normal utilització dels continguts del Portal, els sistemes d’informació o els documents, arxius i tota classe de continguts emmagatzemats en qualsevol equip informàtic de Musicalitza o de qualsevol Artista o Usuari.</p>
            <p>Per accedir als serveis addicionals oferts per Musicalitza, l’Usuari s’haurà de donar d’alta registrant-se en el Portal i generar una contrasenya personal.</p>
            <p>L’Usuari que incompleixi les obligacions enunciades respondrà per tots els danys i perjudicis que pugui causar al Titular i/o a tercers. El Titular es reserva l’exercici de les accions legals que siguin necessàries per a defensar els seus drets.</p>
        </div>
        <h3><br>2.3  Propietat Intel·lectual i Industrial sobre el Portal</h3>
        <div>
            <p>Tots els drets de propietat intel·lectual i industrial sobre el Portal estan legalment reservats. Tots els continguts del Portal, incloent, a títol enunciatiu però no limitatiu, textos, imatges, vídeos, sons, marques, noms comercials, logotips, gràfics, estructura i disseny, combinacions de colors o formes de presentació, codi font, animacions, software o aplicacions informàtiques, sigui quin sigui el seu format, llenguatge de programació i forma de representació, així com el nom de domini <a href="http://www.ioc-musicalitza.tk/">www.ioc-musicalitza.tk</a>, són propietat del Titular, o bé el Titular n’ha adquirit els corresponents drets dels seus propietaris, i estan protegits per les lleis i els tractats internacionals en matèria de propietat intel·lectual i, si escau, industrial, així com per la normativa reguladora dels noms de domini.</p>
            <p>Per mitjà d’aquest Avís Legal no se cedeix cap dret de propietat intel·lectual o industrial sobre el Portal ni sobre cap dels seus continguts o elements integrants, i queden expressament prohibits a l’Usuari la reproducció, transformació, distribució, extracció, reutilització, reenviament, posada a disposició, comunicació pública o utilització de qualsevol naturalesa, per qualsevol mitjà o procediment, del Portal i/o de qualsevol dels seus continguts, llevat allò que es prevegi expressament aquí.</p>
            <p>Només es permet la utilització o reproducció, total o parcial, sense ànim de lucre, dels continguts del Portal sempre i quan es compleixin totes les següents condicions: (i) es comuniqui la referida utilització prèviament al Titular; (ii) es faci constar la font; (iii) s’inclogui un hipervincle al Portal; i (iv) es faci un reconeixement explícit de l’autoria. També es podran utilitzar o reproduir els continguts del Portal en els casos permesos explícitament en els articles 31 a 40 de la Llei de Propietat Intel·lectual espanyola (Reial Decret Legislatiu 1/1996, de 12 d’abril).</p>
            <p>L’Usuari s’obliga a utilitzar els continguts del Portal de forma diligent, correcta i lícita, i, en particular, es compromet a no utilitzar-los de forma, amb finalitats o efectes contraris a la llei, a la moral i als bons costums o a l’ordre públic, ni de qualsevol forma que permeti suprimir, eludir o manipular el “copyright” i la resta de dades identificatives dels drets del Titular o dels Artistes incorporats als continguts, així com els dispositius tècnics de protecció, les marques d’aigua, les empremtes digitals o qualssevol altres mecanismes de seguretat o d’informació.</p>
            <p>Queda prohibit l’ús de marcs (<em>frames</em>) o de qualsevol altre mecanisme destinat a ocultar l’origen o la font dels continguts, qualsevol ús, transformació o explotació d’aquests amb finalitats comercials, promocionals o contràries a la llei, a la moral o a l’ordre públic, que siguin susceptibles de lesionar els interessos o perjudicar la imatge de Musicalitza o de tercers legítims, que constitueixin competència deslleial o, en general, en contra d’allò previst en aquest Avís Legal.</p>
            <p>Queda també prohibit descompilar, desensamblar, realitzar enginyeria inversa, sublicenciar o transmetre de qualsevol forma, traduir o realitzar obres derivades dels programes d’ordinador necessaris per al funcionament, l’accés i la utilització del Portal i dels serveis que conté, així com realitzar, respecte de tots o part dels referits programes, qualsevol dels actes d’explotació referits en els paràgrafs anteriors. L’Usuari s’abstindrà en tot cas de suprimir, alterar, eludir o manipular qualsevol dispositiu de protecció o sistema de seguretat del Portal.</p>
            <p>L’Usuari es compromet a respectar els drets enunciats i a evitar qualsevol actuació que pogués perjudicar-los. El Titular es reserva en tot cas l’exercici dels mitjans o les accions legals que li corresponguin en defensa dels seus legítims drets de propietat intel·lectual i industrial.</p>
            La legitimitat i la titularitat dels drets de propietat intel·lectual o industrial sobre els continguts aportats pels Usuaris, pels Clients i/o pels Artistes és de l’exclusiva responsabilitat de la persona que els hagi aportat. Als efectes de preservar els possibles drets de propietat intel·lectual, en cas que qualsevol Usuari o un tercer consideri que s’ha produït una vulneració dels seus legítims drets a causa de la introducció d’un determinat contingut al Portal, la persona afectada haurà de notificar aquesta circumstància, per escrit, a Musicalitza, a l’adreça de correu electrònic <a href="mailto:admin@ioc-musicalitza.tk">admin@ioc-musicalitza.tk</a>, indicant: (i) dades de caràcter personal identificatives de l’interessat titular dels drets presumptament infringits (si la reclamació la presenta un tercer diferent de l’interessat, haurà d’indicar la representació que exerceix ); (ii) els continguts protegits per drets de propietat intel·lectual i la seva ubicació exacta en el Portal; (iii) acreditació de l’existència, la titularitat i la vigència dels referits drets de propietat intel·lectual; (iv) declaració expressa en la qual la persona interessada es responsabilitzi de la veracitat de les dades i la informació que hagi facilitat en la notificació a què es refereix aquest paràgraf.</div>
        <h3><br>2.4 Política de Privacitat i Cookies</h3>
        <p>La política de privacitat i de cookies del Portal <a href="http://www.ioc-musicalitza.tk/">www.ioc-musicalitza.tk</a> queda determinada per allò establert en l’apartat “<a href="politica-de-privacitat.php">Política de Privacitat i Cookies</a>” </p>
        <h3><br>2.5 Limitació de Responsabilitat</h3>
        <div>
            <p>El Portal conté <strong>enllaços</strong> (hipervincles com per exemple botons, links, banners, etc.) a altres pàgines web, i ho fa en la creença de bona fe que aquests continguts compleixen amb la legalitat. Això no significa que Musicalitza aprovi o recomani els referits continguts de tercers. Si l’Usuari hi accedeix, ho fa sota la seva responsabilitat. El Titular no assumeix garanties sobre la veracitat, l’exactitud o l’actualització dels continguts, serveis, textos, gràfics i vincles d’aquells llocs web.</p>
            <p>Els enllaços o continguts de tercers que apareixen al Portal, entre ells els comentaris al blog o els comentaris i valoracions dels Usuaris sobre els Albums o els Artistes, es faciliten amb la finalitat d’ampliar la informació o indicar altres punts de vista, de forma que pertanyen al seu autor o signatari, i no reflecteixen necessàriament els punts de vista de Musicalitza, del seu personal o col·laboradors. La seva inclusió en el Portal no implica l’acceptació dels referits continguts, ni l’associació de Musicalitza amb els seus responsables, per la qual cosa Musicalitza no garanteix l’absència de virus o altres elements lesius en els dits continguts i rebutja tota responsabilitat en relació amb ells, així com pels danys que poguessin causar-se per qualsevol motiu en l’equip informàtic (equip i aplicacions), documents o fitxers dels Usuaris.</p>
            <p>Musicalitza només serà responsable pels continguts de tercers publicats al Portal de conformitat amb el que estableix la Llei 34/2002, d’11 de juliol, de Serveis de la Societat de la Informació i de Comerç Electrònic (“<strong>LSSI</strong>”), en cas que, havent tingut coneixement efectiu de la seva il·licitud, no elimini o bloquegi els corresponents continguts dins d’un termini raonable. Musicalitza suprimirà, a la major brevetat possible tan bon punt en sigui advertit, qualsevol enllaç a llocs web els continguts del qual siguin contraris a la llei, a la dignitat personal o que pogués causar dany, perjudici o induir a error als Usuaris. Si l’Usuari tingués coneixement de l’existència d’algun enllaç a continguts il·lícits, il·legals, contraris a les lleis o que poguessin suposar una infracció de drets de propietat intel·lectual i/o industrial, ho haurà de notificar immediatament al Titular per tal que aquest pugui adoptar les mesures oportunes al respecte. Per això demanem la vostra col·laboració tan bon punt tingueu coneixement d’algun enllaç o contingut d’aquestes característiques, i us sol·licitem que ens envieu un email a l’adreça <a href="mailto:admin@ioc-musicalitza.tk">admin@ioc-musicalitza.tk</a>. </p>
            <p>Musicalitza no garanteix la fiabilitat, la disponibilitat o la continuïtat del funcionament del Portal ni dels seus continguts per motius tècnics, de seguretat, control o manteniment del servei, per errors deguts al servidor que els allotja o d’altres intermediaris o proveïdors, per atacs contra el sistema informàtic, ni per qualssevol altres motius derivats de causes que s’escapin del nostre control, i per això rebutgem, en la màxima mesura permesa per la legislació vigent, qualsevol responsabilitat, directa o indirecta, per aquests motius.</p>
            <p>L’Usuari és el responsable de prendre les precaucions necessàries per a comprovar la no existència de virus o altre tipus de programes de naturalesa danyina. Musicalitza no es responsabilitza per l’existència d’elements lesius (per exemple, virus) que poguessin ocasionar danys o el mal funcionament en els sistemes, software, hardware, programes, documents i fitxers electrònics de l’Usuari. De la mateixa manera, Musicalitza no es responsabilitza dels possibles danys que com a conseqüència d’aquells pugui causar l’Usuari a tercers. Musicalitza tampoc és responsable ni garanteix la invulnerabilitat del Portal i/o la inexpugnabilitat de les mesures de seguretat que s’hi adoptin. Musicalitza no assumeix cap responsabilitat per una eventual manca d’utilitat o de rendiment dels continguts, els productes i serveis oferts o prestats en el Portal.</p>
            <p>L’Usuari utilitza aquest Portal voluntàriament i sota la seva única i exclusiva responsabilitat, de manera que el Titular no serà responsable, contractual ni extracontractualment, dels danys, directes o indirectes, imprevistos, emergents o punitius, resultants de l’accés o ús d’aquest Portal per part dels Usuaris, o de qualsevol actuació realitzada sobre la base de la informació que s’hi facilita. Amb caràcter general, la navegació pel Portal no exigeix la prèvia subscripció o el registre dels Usuaris. No obstant això, Musicalitza condiciona la utilització d’alguns dels seus serveis o la compra de productes a la prèvia complementació del corresponent registre d’Usuari, seleccionant l’identificador (ID o login) i la contrasenya que l’Usuari es compromet a conservar i a usar amb la deguda diligència. L’ús de la contrasenya és personal i intransferible, i no n’està permesa la cessió, ni tan sols temporal, a tercers. En aquest sentit, l’Usuari haurà d’adoptar les mesures necessàries per a custodiar la contrasenya que hagi seleccionat, evitant-ne l’ús per tercers. En conseqüència, l’Usuari és l’únic responsable de la utilització de la seva contrasenya, amb absoluta indemnitat per a Musicalitza. En el cas que l’Usuari conegui o sospiti del mal ús de la seva contrasenya per part de tercers, ho haurà de posar en coneixement de Musicalitza el més aviat possible.</p>
            <p>El registre dels Usuaris al Portal s’efectuarà en la forma expressament indicada en el propi servei. Tota la informació que proporcioni l’Usuari a través del Portal haurà de ser veraç i exacta. A aquests efectes, l’Usuari garanteix l’autenticitat de totes aquelles dades que comuniqui com a conseqüència de la complementació dels formularis necessaris per al registre o la subscripció dels serveis. Igualment, serà responsabilitat de l’Usuari mantenir tota la informació proporcionada a Musicalitza permanentment actualitzada, de forma que respongui en cada moment a la situació real de l’Usuari. En to cas l’Usuari serà l’únic responsable de les manifestacions falses o inexactes que realitzi, i dels perjudicis que ocasioni a Musicalitza o a tercers per la informació que proporcioni. L’Usuari s’obliga a respectar les lleis aplicables i els drets de tercers en utilitzar els continguts i serveis del Portal.</p>
            <p>L’Usuari no utilitzarà continguts injuriosos o calumniosos, i no promourà, oferirà o distribuirà continguts o productes pornogràfics o que vulnerin les lleis de protecció de menors, no molestarà altres Usuaris (especialment a través de spam), no utilitzarà continguts protegits legalment (per exemple per la legislació sobre propietat intel·lectual i industrial) sense tenir-hi dret o gaudir de la preceptiva autorització, no farà publicitat, oferirà o distribuirà béns o serveis protegits legalment, i no realitzarà ni fomentarà accions contràries a la lliure competència o susceptibles de ser reputades com a actes de competència deslleial, incloent-hi aquelles accions encaminades a la captació de clients.</p>
        </div>
        <h3>2.6  Hiperenllaços</h3>
        <p>L’Usuari i, en general, qualsevol persona física o jurídica que tingui intenció d’establir un hiperenllaç o dispositiu tècnic d’enllaç des del seu lloc web al Portal haurà d’obtenir una autorització prèvia i per escrit del Titular. En qualsevol cas, l’establiment d’aquests hiperenllaços no comporta l’existència de relacions entre el Titular i el propietari del lloc web en el qual s’estableixi l’hiperenllaç, ni l’acceptació o aprovació, per part del Titular, dels continguts o serveis del lloc web enllaçat.</p>
        <h3>2.7  Servei de puntuacions, comentaris i valoracions </h3>
        <div>Els Usuaris registrats al Portal poden puntuar i deixar valoracions o comentaris a les fitxes Artistes i als seus Albums. El registre es realitzarà mitjançant un nom d’Usuari i una contrasenya o clau personal intransferible, l’Usuari assumeix les conseqüències d’infringir la confidencialitat i del mal ús de les claus i els codis d’accés. Podràn accedir al servei de puntuacions, comentaris i valoracions les persones majors de 14 anys. En cas de ser menor de 14 anys, caldrà el consentiment per escrit dels pares o tutors dels menors.<br><br></div>
        <div>Tot Usuari es compromet a utilitzar el servei de puntuacions, comentaris i valoracions de conformitat amb la llei, l’Avís Legal, incloent les Condicions Generals d’Ús del Portal, així com amb la moral, l’ordre públic i els bons costums generalment acceptats.<br><br></div>
        <div>L’usuari s’obliga doncs a no utilitzar el servei amb finalitats o efectes il·lícits, lesius dels drets i interessos de tercers, o que de qualsevol forma pugui danyar, inutilitzar, sobrecarregar o deteriorar el servei o impedir-ne la normal utilització o gaudi per part d’altres Usuaris. En particular, i a títol merament enunciatiu però no exhaustiu, queda prohibida la transmissió, difusió o posada a disposició de tercers, a través del servei, d’informacions, missatges, gràfics, arxius de so i/o imatge, fotografies, gravacions, software i, en general, qualsevol classe de material, dades o continguts que: (i) de qualsevol forma molestin, assetgin, amenacin o abusin d’altres Usuaris, Artistes o tercers; (ii) incorporin continguts obscens o censurables o que puguin ferir la sensibilitat de qualssevol tercers que hi puguin accedir; (iii) difonguin continguts susceptibles d’infringir o vulnerar els drets legals dels altres, com per exemple material difamatori o aquells el contingut dels quals infringeixi drets de propietat intel·lectual o industrial; (iv) animin a altres a infringir les Condicions Generals d’Ús del Portal, de l’Avís Legal o la resta de condicions legals del Portal; (v) es publiquin amb la intenció de fer-se passar per membres de l’equip de Musicalitza o per un altre Usuari a través de l’ús d’una identificació similar o de qualsevol altre mètode o dispositiu; (vi) s’utilitzin amb finalitats comercials, publicitàries o promocionals, així com per a enviar correu brossa, spam, cadenes o distribució massiva de missatges no sol·licitats; (vii) infringeixin la normativa sobre secret de les comunicacions.<br><br></div>
        <div>Queda expressament prohibida la venda, promoció i distribució de serveis o productes a través de l’espai habilitat per a comentar els Albums dels Artistes o les entrades del blog. Musicalitza es reserva el dret de retirar i/o suspendre qualsevol Usuari per l’incompliment d’allò previst en les Condicions Generals d’Ús o en l’Avís Legal, així com d’eliminar, retirar i/o suspendre qualsevol missatge que incorpori continguts com els enunciats en el paràgraf anterior, sense necessitat de preavís o posterior notificació.<br><br></div>
        <div>Els missatges i els continguts manifestats pels Usuaris en el servei de puntuacions, valoracions i comentaris només reflecteixen l’opinió dels seus autors, i el seu contingut és únicament i exclusivament responsabilitat d’aquests. Musicalitza no es fa en cap cas responsable pels missatges enviats pels seus Usuaris, i exclou qualsevol responsabilitat pels danys i perjudicis de qualsevol naturalesa que puguin derivar de l’ús del servei que en fan els Usuaris, o que puguin ser deguts a l’accés i, si escau, a la interceptació, eliminació, modificació o manipulació, per part de tercers autoritzats, o no, dels missatges que els Usuaris difonguin o posin a disposició de tercers a través del servei de puntuacions, valoracions i comentaris. Musicalitza no garanteix la disponibilitat, la continuïtat ni la infal·libilitat del funcionament del servei, i en conseqüència exclou, en la màxima mesura permesa per la llei, qualsevol responsabilitat pels danys i perjudicis de tota mena que puguin ser deguts a la manca de disponibilitat o de continuïtat del funcionament del Portal i dels seus serveis, així com als errors en l’accés a les diferents pàgines web o a aquelles des de les quals, si escau, es prestin els referits serveis.<br><br></div>
        <div>Tenint en compte que les mesures de seguretat a Internet no són inexpugnables, pel que fa a la privacitat i la seguretat de la utilització del servei de puntuacions, valoracions i comentaris, Musicalitza no garanteix que tercers, autoritzats o no, no puguin tenir coneixement de la classe, les condicions, les característiques i les circumstàncies de l'ús que els Usuaris fan del servei, o que puguin accedir i, si escau, interceptar, eliminar, alterar, modificar o manipular els missatges i comunicacions de qualsevol tipus que els Usuaris difonguin o posin a disposició de tercers a través dels referits serveis.<br><br></div>

        <h2>Protecció de dades</h2>
        <h3>3.1  Propietat Intel·lectual</h3>
        <p>Addicionalment a allò previst en les Condicions Generals d’Ús del Portal, també aplicables a les compravendes d’Obres i Reproduccions entre Musicalitza i els Clients, Musicalitza informa als seus Clients que els autors de els Albums exposades al Portal manifesten ser els legítims titulars dels drets de propietat intel·lectual de les dites Obres i, per tant, els Usuaris es comprometen a no utilitzar els Albums o les Reproduccions de cap forma que pogués perjudicar els referits drets.</p>
        <p>Igualment, els Clients han de tenir en compte que la compra de l’exemplar físic d’una Obra no implica la cessió al Client dels drets de propietat intel·lectual sobre aquella Obra, que segueixen en poder de l’Artista o d’aquells titulars als quals l’Artista els hagi cedit. A títol merament enunciatiu, la compra d’una Obra no comporta la cessió al Client dels drets de reproducció, distribució, comunicació pública o transformació, llevat dels que siguin estrictament necessaris per al gaudi privat de l’Obra per part del Client. Mitjançant la compra de l’Obra, el Client només adquireix el dret de propietat sobre l’exemplar físic de la referida Obra, sens perjudici que l’ús que pugui fer de l’Obra sigui subsumible en algun dels límits o excepcions als drets d’autor previstos en la normativa sobre propietat intel·lectual.</p>
        <p>En el cas de reproduccions d’obres de grans mestres de l’art, com que aquestes es troben en domini públic el Client que les adquireixi estarà facultat per a usar-les com consideri convenient, sens perjudici però dels drets morals sobre les referides obres.</p>

        <h3>3.2  Protecció de dades de caràcter personal</h3>
        <p>Addicionalment a allò establert en la Política de Privacitat i Cookies del Portal, que és íntegrament aplicable a tota transacció o compravenda d’Obres i Reproduccions a través del Portal, Musicalitza informa als seus Clients:</p>
        <ul>
            <li>Que les dades personals dels Clients seran incorporades als fitxers de titularitat de Musicalitza, degudament declarats i inscrits al Registre de l’Agència de Protecció de Dades.<br><br></li>
            <li>Que els Usuaris i Clients podran, en qualsevol moment, de conformitat amb allò previst a la Llei Orgànica 15/1999, de 13 de desembre, de Protecció de Dades de Caràcter Personal (en endavant, la “<strong>LOPD</strong>”) i en la seva normativa de desenvolupament, exercir els drets d’accés, rectificació, cancel·lació i oposició de les seves dades personals mitjançant petició escrita enviada per correu electrònic a l’adreça <a href="mailto:lopd@ioc-musicalitza.tk">lopd@ioc-musicalitza.tk</a>. </li>
        </ul>

        <h2>4. Modificacions i actualitzacions de l'avis legal</h2>
        <p>El Titular es reserva la facultat d’efectuar, en qualsevol moment i sense necessitat de preavís, modificacions i actualitzacions de la informació i els continguts inclosos en el Portal i en aquest Avís Legal. En conseqüència, serà responsabilitat de tot Usuari del Portal l’atenta lectura de l’Avís Legal vigent cada vegada que accedeixi al Portal, de forma que si l’Usuari no està d’acord amb qualsevol dels termes disposats en l’Avís Legal, haurà d’abstenir-se d’usar el Portal. En cas contrari, és a dir, si malgrat tot utilitza el Portal, s’entendrà que accepta tàcitament tots els termes i condicions de l’Avís Legal. La vigència temporal d’aquest Avís Legal coincideix, per tant, amb el temps de la seva exposició, fins que en siguin modificats total o parcialment els seus termes i condicions, moment en el qual passarà a tenir vigència l’Avís Legal modificat.</p>
        <h2>5. Nul·litat</h2>
        <p>En el cas que qualsevol clàusula d’aquest Avís Legal fos declarada nul·la, la resta del clausulat romandrà vigent i s’haurà d’interpretar de conformitat amb la voluntat de les parts i la finalitat del text.</p>
        <h2>6. Llei aplicable i jurisdicció</h2>
        <p>Totes les qüestions o controvèrsies relatives als continguts i a l’aplicació d’aquest Avís Legal o a l’activitat de Musicalitza en virtut dels termes i condicions de l’Avís legal es regiran per la legislació espanyola.</p>
        <p>La competència per a resoldre les referides qüestions o controvèrsies correspondrà als Jutjats i Tribunals de la ciutat de Barcelona (Espanya), als quals se sotmeten expressament les parts, amb renúncia a qualsevol altre fòrum que els pogués correspondre, si així ho permet la llei.</p>
        <p>Copyright 2018, Musicalitza. Prohibida la seva reproducció total o parcial. Reservats tots els drets.</p>
        <p>Última versió: 10 de maig de 2018.</p>
    </div>
</div>


<?php
require 'footer.php';
