<?php
require 'header.php';
?>

<div id="politica-de-privacitat" class="container top40 bottom80">
    <div class="row userPanelSectionBox">

        <h1 class="bottom20">Política de Privacitat i Cookies</h1>
        <h2>Protecció de dades personals</h2>
        <hr><p>Aquesta Política de Privacitat i cookies és part integrant de l’Avís Legal del lloc web <a href="http://www.ioc-musicalitza.tk">www.ioc-musicalitza.tk</a> (en endavant, el “<strong>Portal</strong>”).</p>
        <div>En compliment d’allò previst en la Llei Orgànica 15/1999, de 13 de desembre, de Protecció de Dades de Caràcter Personal (en endavant, la “<strong>LOPD</strong>”) i la seva normativa de desenvolupament, així com en la Llei 34/2002, d’11 de juliol, de Serveis de la Societat de la Informació i del Comerç Electrònic (“<strong>LSSI</strong>”), Xavier Domènech Corbella, fundador i CEO de Musicalitza (en endavant, el “<strong>Titular</strong>”), li comunica que:<br><br></div>
        <div>La informació que rep el Titular de cada persona que usa el Portal, ja sigui com a usuari o com a artista col·laborador (en endavant, l’“<strong>Usuari</strong>” o “<strong>Vostè</strong>”), a través de les consultes online, del registre en el Portal, de missatges a través d’aplicacions mòbils, de missatges i consultes a través de xarxes socials, o de l’enviament de qualssevol formularis o correus electrònics, és tractada amb la màxima confidencialitat.<br><br></div>
        <div>En navegar pel Portal, de forma automàtica Vostè facilita al servidor de la web informació relativa a la seva direcció d’IP (número que s’assigna al seu ordinador en accedir a internet i que permet el reconeixement i la comunicació entre els diferents ordinadors i servidors), la data i hora de l’accés, l’hipervincle que l’ha reenviat al Portal, el seu sistema operatiu i el navegador utilitzat. Sens perjudici que l’Agència Espanyola de Protecció de Dades (en endavant, l’“<strong>AEPD</strong>”) considera la IP com a dada de caràcter personal, el Titular no pot obtenir per si sol, ni té intenció de fer-ho llevat que se li causi algun perjudici, cap informació sobre el titular de la connexió a internet a la qual correspon. Aquestes dades seran guardades i utilitzades únicament per al control i la realització d’estadístiques d’accés i visites a la web, i en cap cas seran comunicades o cedides a tercers.<br><br></div>
        <div>En marcar la casella d’acceptació de la Política de Privacitat i Cookies, Vostè manifesta haver llegit, comprès i acceptat expressament aquesta Política de Privacitat i Cookies, i atorga el seu consentiment inequívoc, informat i exprés al tractament de les seves dades personals de conformitat amb allò estipulat en aquest document.<br><br></div>
        <div>En omplir el formulari de contacte del Portal i fer clic sobre el botó “Enviar”, es generarà un email adreçat al Titular, sense que es dugui a terme cap tractament de dades de caràcter personal. L’usuari no està obligat a utilitzar el formulari de contacte ni a emplenar totes les seves dades, si no ho desitja. Tanmateix, si desitja formular qualsevol tipus de consulta al Titular mitjançant el formulari de contacte del Portal i obtenir la resposta del Titular, haurà d’emplenar almenys els camps marcats com a obligatoris i senyalitzats amb un asterisc (*). En cas de no emplenar els camps obligatoris, el Titular es reserva el dret de no tramitar sol·licituds incompletes.<br><br></div>
        <div>En registrar-se com a artista o com a usuari o client en el Portal, Vostè haurà d’emplenar els camps marcats amb asterisc (*) en el formulari de registre. Igualment, en efectuar una compra a través del Portal (per exemple, en comprar una obra d’art si Vostè és usuari/client del Portal, o en subscriure el servei de Destacats VIP si Vostè és artista), també haurà d’emplenar els camps obligatoris amb les seves dades per tal que poguem gestionar la seva compra. En ambdós casos, Vostè estarà enviant dades personals al Titular.<br><br>Les seves dades seran incorporades a un fitxer de dades de caràcter personal propietat del Titular (el “<strong>Fitxer</strong>”), i seran tractades amb les següents finalitats: <br><br>(i) respondre les seves consultes, els seus suggeriments o queixes, donant curs a la seva sol·licitud; <br>(ii) crear el seu perfil d’usuari/client o artista, per tal que Vostè pugui utilitzar totes les funcionalitats que Musicalitza ofereix a tots els seus usuaris/clients i artistes, principalment la compra d’obres d’art (usuaris/clients), l’exposició, promoció i venda d’obres d’art (artistes), i la participació en els espais habilitats per a fòrum o comentaris i valoracions (ambdós); <br>(iii) gestionar la compra i la venda d’obres d’art;<br> (iv) enviar-li comunicacions comercials publicitàries a través de mitjans electrònics o analògics relacionades amb els serveis oferts pel Titular; i <br>(v) gestionar qualsevol altra relació entre Vostè i el Titular. El contingut del Fitxer està format, principalment, per les dades dels usuaris/clients i dels artistes de Musicalitza. El Titular no emmagatzema dades bancàries, de pagament o de targetes de crèdit/dèbit dels usuaris/clients i els artistes del Portal. Les seves dades no seran comunicades ni cedides a tercers sense el seu consentiment exprés.<br><br></div>
        <div>El Titular manifesta un compliment escrupolós de la normativa sobre la protecció de dades de caràcter personal i en especial de la LOPD i les seves normes reglamentàries de desenvolupament. En conseqüència, el Fitxer es troba degudament inscrit en el registre General de l’AEPD i s’hi apliquen les mesures de seguretat, tant tècniques com organitzatives, establertes en la normativa sobre protecció de dades de caràcter personal (en particular, en el Reial Decret 1720/2007, de 21 de desembre, pel qual s’aprova el Reglament de desenvolupament de la LOPD) per a evitar qualsevol accés, alteració, pèrdua o tractament no autoritzats, i necessàries per a garantir la confidencialitat i la integritat de les dades tractades. No obstant això, la seguretat tècnica en un mitjà com internet no és inexpugnable i poden produir-se actuacions doloses de tercers, si bé el Titular posa tots els mitjans al seu abast per evitar aquest tipus d’actuacions.<br><br></div>
        <div>Vostè té dret a accedir al referit Fitxer per tal de consultar les seves dades, rectificar-les o cancel·lar-les, així com a oposar-se al seu tractament, amb les excepcions i els límits establerts en la legislació aplicable. En cas que desitgi exercir els drets referits, només cal que adreci al Titular una sol·licitud signada a l’adreça de correu electrònic <a href="mailto:lopd@ioc-musicalitza.tk">lopd@ioc-musicalitza.tk</a>, adjuntant-hi una fotocòpia digitalitzada del seu D.N.I. o document equivalent, i indicant de forma precisa l’objecte de la seva sol·licitud. En el lloc web de l’AEPD té a la seva disposició models de formularis i més informació al respecte.<br><br></div>
        <div>El Portal pot contenir enllaços a altres llocs web que pertanyen i són gestionats per tercers. Tots ells disposen de les seves pròpies polítiques de privacitat, de cookies i condicions d’ús, de forma que el Titular no assumirà cap responsabilitat pel contingut d’aquestes polítiques ni pels continguts i la informació inclosa en els referits llocs web. En conseqüència, li recomanem que llegeixi i revisi amb atenció la política de privacitat i cookies i les condicions d’ús de cada lloc web que visiti.<br><br></div>
        <div>El Titular es reserva el dret de modificar, en qualsevol moment i a la seva exclusiva discreció, els termes d’aquesta Política de Privacitat. Per aquest motiu, li recomanem que consulti el seu contingut cada vegada que accedeixi al Portal, a fi de conèixer les possibles actualitzacions o canvis introduïts.<br><br></div>
        <h2>Ús de cookies</h2>
        <hr><p>Una cookie és un fitxer que es descarrega al seu ordinador en accedir a determinades pàgines web. Les cookies permeten a una pàgina web, entre altres coses, emmagatzemar i recuperar informació sobre els hàbits de navegació d’un usuari o del seu equip i, depenent de la informació que continguin i de la forma com utilitzi el seu equip, poden utilitzar-se per a reconèixer l’usuari. Segons l’AEPD (<a href="http://www.agpd.es" target="_blank">www.agpd.es</a>), les cookies poden classificar-se entre pròpies i de tercer, i, segons el temps que romanen activades en l’equip terminal, podem distingir entre els següents tipus:</p>
        <div>(i) <strong><em>Cookies de sessió</em>:</strong> Són un tipus de cookies dissenyades per a recollir i emmagatzemar dades mentre l’usuari accedeix a una pàgina web. Se solen utilitzar per a emmagatzemar informació que només interessa conservar per a la prestació del servei sol·licitat per l’usuari en una sola ocasió (p.ex. una llista de productes adquirits).<br><br></div>
        <div>(ii) <strong><em>Cookies persistents</em>:</strong> Són un tipus de cookies en què les dades segueixen emmagatzemades en el terminal i poden ser accedides i tractades durant un període definit pel responsable de la cookie, i que pot anar d’una minuts a diversos anys.</div>
        <div>Segons la seva finalitat, podem distingir entre:</div>
        <div>(i) <em>Cookies tècniques</em>: Són aquelles que permeten a l’usuari la navegació a través d’una pàgina web, plataforma o aplicació, i la utilització de les diferents opcions o serveis que hi existeixin, com, per exemple, controlar el tràfic i la comunicació de dades, identificar la sessió, accedir a parts d’accés restringit, recordar els elements que integren una comanda, realitzar el procés de compra d’una comanda, realitzar la sol·licitud d’inscripció o participació en un esdeveniment, utilitzar elements de seguretat durant la navegació, emmagatzemar continguts per a la difusió de vídeos o so o compartir continguts a través de xarxes socials.<br><br></div>
        <div>(ii) <strong><em>Cookies de personalització</em>:</strong> Són aquelles que permeten a l’usuari accedir al servei amb algunes característiques de caràcter general predefinides en funció d’una sèrie de criteris en el terminal de l’usuari, com per exemple l’idioma, el tipus de navegador a través del qual s’accedeix al servei, la configuració regional des de la qual s’accedeix al servei, etc.<br><br></div>
        <div>(iii) <strong><em>Cookies d’anàlisi</em>:</strong> Són aquelles que permeten al seu responsable el seguiment i l’anàlisi del comportament dels usuaris dels llocs web als quals estan vinculades. La informació recollida mitjançant aquest tipus de cookies s’utilitza en la medició de l’activitat dels llocs web, aplicació o plataforma, i per a l’elaboració de perfils de navegació dels usuaris d’aquests llocs, aplicacions i plataformes, a fi d’introduir-hi millores en funció de l’anàlisi de les dades d’ús que en fan els usuaris del servei.<br><br></div>
        <div>(iv) <strong><em>Cookies publicitàries</em>:</strong> Són aquelles que permeten la gestió, de la forma més eficaç possible, dels espais publicitaris que, si escau, l’editor hagi inclòs en una pàgina web, aplicació o plataforma des de la qual presta el servei sol·licitat en base a criteris com el contingut editat o la freqüència amb la qual es mostren els anuncis.<br><br></div>
        <div>(v)<strong> <em>Cookies de publicitat comportamental</em>:</strong> Són aquelles que permeten la gestió, de la forma més eficaç possible, dels espais publicitaris que, si escau, l’editor hagi inclòs en una pàgina web, aplicació o plataforma des de la qual presta el servei sol·licitat. Aquestes cookies emmagatzemen informació del comportament dels usuaris obtinguda a través de l’observació continuada dels seus hàbits de navegació, la qual cosa permet desenvolupar un perfil específic per a mostrar publicitat en funció d’aquest.<br><br></div>
        <div>Aquest Portal utilitza cookies pròpies i de tercers. Utilitzem cookies tècniques i de personalització amb les finalitats de gestionar la sessió d’usuaris i dels artistes registrats, els comentaris al blog o en altres apartats del Portal, de presentar el portal en l’idioma corresponent a la configuració regional des de la qual l’usuari accedeix al servei i permetre al nostre servidor presentar pàgines web personalitzades que puguin convertir la visita al Portal en una experiència individual per a l’usuari i ajustada a les seves preferències personals. Igualment, utilitzem cookies publicitàries i de publicitat comportamental per a gestionar de la forma més eficaç possible l’oferta dels espais publicitaris que hi ha al Portal, tot adequant el contingut de l’anunci al contingut del servei sol·licitat o a l’ús que en faci l’usuari del Portal. A aquest fi analitzem els seus hàbits de navegació a internet i li podem mostrar publicitat relacionada amb el seu perfil de navegació.<br><br></div>
        <div>També utilitzem cookies de Google Analytics per a analitzar les visites i l’activitat dels usuaris durant el seu temps de navegació. Les cookies de Google Analytics proporcionen informació estadística relativa a les visites al Portal (visitants únics, número de pàgines vistes, durada mitjana de les visites, rebots, visites noves, freqüència i vistes recents, interaccions, pàgines visitades, etc.), dades demogràfiques (idioma, ciutat, país/regió), sistema (navegador, sistema operatiu, proveïdor d’accés a internet, etc.), font/mitjà. Google Analytics no proporciona al Titular cap informació sobre la direcció IP real de l’usuari, de forma que la informació obtinguda a través de cookies és totalment anònima, i en cap cas pot ser associada a un usuari concret i identificat.<br><br></div>
        <div>L’Usuari té la possibilitat de configurar les opcions del seu navegador per a ser avisat de la recepció de cookies i per a permetre, bloquejar o eliminar les cookies instal·lades en el seu equip. Siusplau, consulti les instruccions i els manuals del seu navegador per a ampliar aquesta informació:<br><ul><li>Chrome: <a href="http://support.google.com/chrome/bin/answer.py?hl=es&amp;answer=95647" target="_blank">http://support.google.com/chrome/bin/answer.py?hl=es&amp;answer=95647</a></li>
                <li>Firefox: <a href="http://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-que-los-sitios-we" target="_blank">http://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-que-los-sitios-we</a></li>
                <li>Explorer: <a href="http://windows.microsoft.com/es-es/windows7/how-to-manage-cookies-in-internet-explorer-9" target="_blank">http://windows.microsoft.com/es-es/windows7/how-to-manage-cookies-in-internet-explorer-9</a></li>
                <li>Safari: <a href="https://support.apple.com/kb/PH21411?viewlocale=es_ES&amp;locale=es_ES" target="_blank">https://support.apple.com/kb/PH21411?viewlocale=es_ES&amp;locale=es_ES</a></li>
            </ul></div>
        <p>També pot desactivar les cookies de Google Analytics mitjançant el sistema d’opt-out de Google Analytics, accessible a: <a href="https://tools.google.com/dlpage/gaoptout?hl=es" target="_blank">https://tools.google.com/dlpage/gaoptout?hl=es</a>.</p>
        <div>Qualsevol acció que no sigui el bloqueig de les cookies a través dels mecanismes indicats implica el consentiment per al seu ús. En tot cas, la desactivació, el bloqueig o l’eliminació posterior de les cookies de Google Analytics, a través dels corresponents paràmetres del seu navegador, no afectarà l’accés al Portal.<br><br></div>
        <div>La responsabilitat relativa a l’ús de dades de l’usuari per mitjà de les cookies de Google Analytics correspon exclusivament a Google, Inc. (i no ho fa ni en nom ni per compte del Titular), una companyia de Delaware amb oficina principal a 1600 Amphitheatre Parkway, Mountain View (California), CA 94043, EEUU. La informació que generen aquestes cookies sobre el seu ús del Portal (incloent la seva direcció IP) serà directament transmesa i arxivada per Google en els servidors d’Estats Units. Google utilitzarà aquestes dades, pàgines i cerques, dades de localització i altres hàbits de navegació, per a recopilar informació sobre l’ús del Portal, recopilant informes de l’activitat i prestant altres serveis relacionats amb el Portal i amb l’ús d’internet. El Titular no té accés en cap moment a aquesta informació, sinó únicament a informació agregada que li proporciona posteriorment Google i que no està associada a cap direcció IP. Google (i no el Titular) és qui determina la finalitat del tractament i l’ús de la informació captada per Google Analytics en tot moment, així com el funcionament i la durada de les cookies. Google estableix en les seves condicions que podrà transmetre la referida informació a tercers quan així ho requereixi la legislació, o quan aquests tercers processin la informació per compte de Google.<br><br></div>
        <div>El Titular no pot controlar ni es fa responsable del contingut i la veracitat dels termes i condicions i les polítiques de privacitat de Google referenciades en aquesta política de cookies.</div>


    </div>
</div>


<?php
require 'footer.php';
